### ISSUE TITLE
The playlist contains duplicate items and isn't complete

### ISSUE THREAD

**Issue by poison** [jsoverson/javascript-deobfuscation-AMA#2]
Hi Jarrod,

Just a minor thingy, but your playlist contains the recording of the live stream 1 twice, and doesn't contain all your other amazing live streams.

Thanks a lot for making them!
Nicolas

**Comment by jsoverson** [comment]
Thanks for the note and it should be fixed now. YouTube is not my favorite UI to deal with...

**Comment by poison** [comment]
Yes, it works, thanks a lot for the amazing content!
